ALTER TABLE `ACCOUNT` DROP FOREIGN KEY `ACCOUNT_ibfk_1`;
ALTER TABLE `ACCOUNT` DROP FOREIGN KEY `ACCOUNT_ibfk_2`;
ALTER TABLE `ADMIN` DROP FOREIGN KEY `ADMIN_ibfk_1`;
ALTER TABLE `CORP_ACCOUNT` DROP FOREIGN KEY `CORP_ACCOUNT_ibfk_1`;
ALTER TABLE `CORP_ACCOUNT` DROP FOREIGN KEY `CORP_ACCOUNT_ibfk_2`;
ALTER TABLE `CORPORATION` DROP FOREIGN KEY `CORPORATION_ibfk_1`;
ALTER TABLE `CORPORATION` DROP FOREIGN KEY `CORPORATION_ibfk_2`;
ALTER TABLE `CORPORATION` DROP FOREIGN KEY `CORPORATION_ibfk_3`;
ALTER TABLE `DOCTOR` DROP FOREIGN KEY `DOCTOR_ibfk_1`;
ALTER TABLE `DOCTOR_SPECIALITY` DROP FOREIGN KEY `DOCTOR_SPECIALITY_ibfk_1`;
ALTER TABLE `DOCTOR_SPECIALITY` DROP FOREIGN KEY `DOCTOR_SPECIALITY_ibfk_2`;
ALTER TABLE `MEDICAL_INFORMATION` DROP FOREIGN KEY `MEDICAL_INFORMATION_ibfk_1`;
ALTER TABLE `PATIENT` DROP FOREIGN KEY `PATIENT_ibfk_1`;
ALTER TABLE `PATIENT` DROP FOREIGN KEY `PATIENT_ibfk_2`;
ALTER TABLE `POST` DROP FOREIGN KEY `POST_ibfk_1`;
ALTER TABLE `POST` DROP FOREIGN KEY `POST_ibfk_2`;
ALTER TABLE `POST` DROP FOREIGN KEY `POST_ibfk_3`;
ALTER TABLE `POST` DROP FOREIGN KEY `POST_ibfk_4`;
ALTER TABLE `QUERY` DROP FOREIGN KEY `QUERY_ibfk_1`;
ALTER TABLE `QUERY` DROP FOREIGN KEY `QUERY_ibfk_2`;
ALTER TABLE `USER` DROP FOREIGN KEY `USER_ibfk_1`;
ALTER TABLE `USER` DROP FOREIGN KEY `USER_ibfk_2`;

DROP INDEX `SERVICE_PLAN_ID` ON `ACCOUNT`;
DROP INDEX `ADMIN_ID` ON `ACCOUNT`;
DROP INDEX `ADMIN_ID` ON `ADMIN`;
DROP INDEX `ACCOUNT_ID` ON `CORP_ACCOUNT`;
DROP INDEX `CORP_ID` ON `CORP_ACCOUNT`;
DROP INDEX `CONTACT_ID` ON `CORPORATION`;
DROP INDEX `ADMIN` ON `CORPORATION`;
DROP INDEX `SERVICE_PLAN_ID` ON `CORPORATION`;
DROP INDEX `SPECIALITY` ON `DOCTOR_SPECIALITY`;
DROP INDEX `USER_ID` ON `PATIENT`;
DROP INDEX `ACCOUNT_ID` ON `PATIENT`;
DROP INDEX `PARENT_ID` ON `POST`;
DROP INDEX `QUERY_ID` ON `POST`;
DROP INDEX `POST_BY` ON `POST`;
DROP INDEX `USER_ID` ON `POST`;
DROP INDEX `DOCTOR_ID` ON `QUERY`;
DROP INDEX `PATIENT_ID` ON `QUERY`;
DROP INDEX `USER_ID` ON `USER`;
DROP INDEX `LOGIN_NAME` ON `USER`;
DROP INDEX `CONTACT_ID` ON `USER`;
DROP INDEX `ROLE_NAME` ON `USER`;

DROP TABLE `ACCOUNT`;
DROP TABLE `ADMIN`;
DROP TABLE `CONTACT_INFO`;
DROP TABLE `CORP_ACCOUNT`;
DROP TABLE `CORPORATION`;
DROP TABLE `DOCTOR`;
DROP TABLE `DOCTOR_SPECIALITY`;
DROP TABLE `MEDICAL_INFORMATION`;
DROP TABLE `PATIENT`;
DROP TABLE `POST`;
DROP TABLE `QUERY`;
DROP TABLE `ROLE`;
DROP TABLE `SERVICE_PLAN`;
DROP TABLE `SPECIALITIES`;
DROP TABLE `USER`;

CREATE TABLE `ACCOUNT` (
`ACCOUNT_ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`ADMIN_ID` int(10) UNSIGNED NULL DEFAULT NULL,
`SERVICE_PLAN_ID` int(10) UNSIGNED NOT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
`VERIFIED` tinyint(1) NOT NULL DEFAULT 0,
PRIMARY KEY (`ACCOUNT_ID`) ,
INDEX `SERVICE_PLAN_ID` (`SERVICE_PLAN_ID`),
INDEX `ADMIN_ID` (`ADMIN_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=10;

CREATE TABLE `ADMIN` (
`USER_ID` int(10) UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (`USER_ID`) ,
UNIQUE INDEX `ADMIN_ID` (`USER_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `CONTACT_INFO` (
`CONTACT_ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`EMAIL` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`PRIMARY_PHONE` char(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SECONDARY_PHONE` char(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
`EMAIL_VERIFIED` tinyint(1) NULL DEFAULT 0,
`PHONE_VERIFIED` tinyint(1) NULL DEFAULT 0,
PRIMARY KEY (`CONTACT_ID`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=38;

CREATE TABLE `CORP_ACCOUNT` (
`CORP_MAIL_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CORP_ID` int(10) UNSIGNED NOT NULL,
`ACCOUNT_ID` int(10) UNSIGNED NOT NULL,
PRIMARY KEY (`CORP_MAIL_ID`) ,
INDEX `ACCOUNT_ID` (`ACCOUNT_ID`),
INDEX `CORP_ID` (`CORP_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `CORPORATION` (
`CORP_ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`Name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CONTACT_ID` int(10) UNSIGNED NOT NULL,
`DOMAIN` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ADMIN` int(10) UNSIGNED NULL DEFAULT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
`SERVICE_PLAN_ID` int(10) UNSIGNED NULL,
PRIMARY KEY (`CORP_ID`) ,
INDEX `CONTACT_ID` (`CONTACT_ID`),
INDEX `ADMIN` (`ADMIN`),
INDEX `SERVICE_PLAN_ID` (`SERVICE_PLAN_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=4;

CREATE TABLE `DOCTOR` (
`USER_ID` int(10) UNSIGNED NOT NULL,
PRIMARY KEY (`USER_ID`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `DOCTOR_SPECIALITY` (
`DOCTOR_ID` int(10) UNSIGNED NOT NULL,
`SPECIALITY` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`DOCTOR_ID`, `SPECIALITY`) ,
INDEX `SPECIALITY` (`SPECIALITY`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `MEDICAL_INFORMATION` (
`DOB` date NULL DEFAULT NULL,
`GENDER` enum('MALE','FEMALE','OTHER') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`WEIGHT` tinyint(3) UNSIGNED NULL DEFAULT NULL,
`ALLERGIES` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`USER_ID` int(10) UNSIGNED NOT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
PRIMARY KEY (`USER_ID`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `PATIENT` (
`USER_ID` int(10) UNSIGNED NOT NULL,
`ACCOUNT_ID` int(10) UNSIGNED NULL DEFAULT NULL,
PRIMARY KEY (`USER_ID`) ,
UNIQUE INDEX `USER_ID` (`USER_ID`),
INDEX `ACCOUNT_ID` (`ACCOUNT_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `POST` (
`ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`TEXT` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`QUERY_ID` int(11) NOT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
`PARENT_ID` int(10) UNSIGNED NULL,
`USER_ID` int(10) UNSIGNED NOT NULL,
`POST_BY` enum('DOCTOR','PATIENT','ADMIN') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ID`) ,
INDEX `PARENT_ID` (`PARENT_ID`),
INDEX `QUERY_ID` (`QUERY_ID`),
INDEX `POST_BY` (`POST_BY`),
INDEX `USER_ID` (`USER_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1;

CREATE TABLE `QUERY` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`DOCTOR_ID` int(10) UNSIGNED NULL DEFAULT NULL,
`PATIENT_ID` int(10) UNSIGNED NOT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
PRIMARY KEY (`ID`) ,
INDEX `DOCTOR_ID` (`DOCTOR_ID`),
INDEX `PATIENT_ID` (`PATIENT_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1;

CREATE TABLE `ROLE` (
`ROLE_NAME` enum('DOCTOR','PATIENT','ADMIN') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`ROLE_NAME`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `SERVICE_PLAN` (
`SERVICE_PLAN_ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`DURATION` enum('HALF-YEARLY','YEARLY') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`DEPENDENTS` tinyint(2) UNSIGNED NOT NULL,
`FEE` int(5) UNSIGNED NULL DEFAULT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
`NAME` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`SERVICE_PLAN_ID`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=3;

CREATE TABLE `SPECIALITIES` (
`SPECIALITY` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
PRIMARY KEY (`SPECIALITY`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `USER` (
`USER_ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`FIRST_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`LAST_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`PASSWORD` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CREATED_ON_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UPDATED_ON_DATE` datetime NOT NULL,
`ROLE_NAME` enum('DOCTOR','PATIENT','ADMIN') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CONTACT_ID` int(10) UNSIGNED NOT NULL,
`LOGIN_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`LOGIN_TYPE` enum('FB','GOOGLE','BASIC') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`USER_ID`) ,
UNIQUE INDEX `USER_ID` (`USER_ID`),
UNIQUE INDEX `LOGIN_NAME` (`LOGIN_NAME`),
INDEX `CONTACT_ID` (`CONTACT_ID`),
INDEX `ROLE_NAME` (`ROLE_NAME`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=27
COMMENT='Users of Econsult';


ALTER TABLE `ACCOUNT` ADD CONSTRAINT `ACCOUNT_ibfk_1` FOREIGN KEY (`SERVICE_PLAN_ID`) REFERENCES `SERVICE_PLAN` (`SERVICE_PLAN_ID`);
ALTER TABLE `ACCOUNT` ADD CONSTRAINT `ACCOUNT_ibfk_2` FOREIGN KEY (`ADMIN_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `ADMIN` ADD CONSTRAINT `ADMIN_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `CORP_ACCOUNT` ADD CONSTRAINT `CORP_ACCOUNT_ibfk_1` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`);
ALTER TABLE `CORP_ACCOUNT` ADD CONSTRAINT `CORP_ACCOUNT_ibfk_2` FOREIGN KEY (`CORP_ID`) REFERENCES `CORPORATION` (`CORP_ID`);
ALTER TABLE `CORPORATION` ADD CONSTRAINT `CORPORATION_ibfk_1` FOREIGN KEY (`CONTACT_ID`) REFERENCES `CONTACT_INFO` (`CONTACT_ID`);
ALTER TABLE `CORPORATION` ADD CONSTRAINT `CORPORATION_ibfk_2` FOREIGN KEY (`ADMIN`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `CORPORATION` ADD CONSTRAINT `CORPORATION_ibfk_3` FOREIGN KEY (`SERVICE_PLAN_ID`) REFERENCES `SERVICE_PLAN` (`SERVICE_PLAN_ID`);
ALTER TABLE `DOCTOR` ADD CONSTRAINT `DOCTOR_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `DOCTOR_SPECIALITY` ADD CONSTRAINT `DOCTOR_SPECIALITY_ibfk_1` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `DOCTOR` (`USER_ID`);
ALTER TABLE `DOCTOR_SPECIALITY` ADD CONSTRAINT `DOCTOR_SPECIALITY_ibfk_2` FOREIGN KEY (`SPECIALITY`) REFERENCES `SPECIALITIES` (`SPECIALITY`);
ALTER TABLE `MEDICAL_INFORMATION` ADD CONSTRAINT `MEDICAL_INFORMATION_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `PATIENT` (`USER_ID`);
ALTER TABLE `PATIENT` ADD CONSTRAINT `PATIENT_ibfk_1` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`);
ALTER TABLE `PATIENT` ADD CONSTRAINT `PATIENT_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `POST` ADD CONSTRAINT `POST_ibfk_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `POST` (`ID`);
ALTER TABLE `POST` ADD CONSTRAINT `POST_ibfk_2` FOREIGN KEY (`QUERY_ID`) REFERENCES `QUERY` (`ID`);
ALTER TABLE `POST` ADD CONSTRAINT `POST_ibfk_3` FOREIGN KEY (`POST_BY`) REFERENCES `ROLE` (`ROLE_NAME`);
ALTER TABLE `POST` ADD CONSTRAINT `POST_ibfk_4` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `QUERY` ADD CONSTRAINT `QUERY_ibfk_1` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `DOCTOR` (`USER_ID`);
ALTER TABLE `QUERY` ADD CONSTRAINT `QUERY_ibfk_2` FOREIGN KEY (`PATIENT_ID`) REFERENCES `PATIENT` (`USER_ID`);
ALTER TABLE `USER` ADD CONSTRAINT `USER_ibfk_1` FOREIGN KEY (`CONTACT_ID`) REFERENCES `CONTACT_INFO` (`CONTACT_ID`);
ALTER TABLE `USER` ADD CONSTRAINT `USER_ibfk_2` FOREIGN KEY (`ROLE_NAME`) REFERENCES `ROLE` (`ROLE_NAME`);

