
    create table ACCOUNT (
        ACCOUNT_ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        VERIFIED boolean default '0',
        ADMIN_ID bigint,
        SERVICE_PLAN_ID bigint,
        primary key (ACCOUNT_ID)
    );
    create table ADMIN (
        USER_ID bigint not null,
        primary key (USER_ID)
    );
    create table CONTACT_INFO (
        CONTACT_ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        EMAIL varchar(255),
        EMAIL_VERIFIED boolean,
        PHONE_VERIFIED boolean,
        PRIMARY_PHONE varchar(255),
        SECONDARY_PHONE varchar(255),
        primary key (CONTACT_ID)
    );
    create table CORPORATION (
        CORP_ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        DOMAIN varchar(255),
        NAME varchar(255),
        ADMIN bigint,
        CONTACT_ID bigint,
        SERVICE_PLAN_ID bigint,
        primary key (CORP_ID)
    );
    create table CORP_ACCOUNT (
        CORP_MAIL_ID varchar(255) not null,
        ACCOUNT_ID bigint,
        CORP_ID bigint,
        primary key (CORP_MAIL_ID)
    );
    create table DOCTOR (
        USER_ID bigint not null,
        primary key (USER_ID)
    );
    create table DOCTOR_SPECIALITY (
        DOCTOR_ID bigint not null,
        SPECIALITY varchar(255) not null,
        primary key (DOCTOR_ID, SPECIALITY)
    );
    create table MEDICAL_INFORMATION (
        USER_ID bigint not null,
        UPDATED_ON_DATE timestamp,
        ALLERGIES varchar(255),
        DOB date,
        GENDER varchar(255),
        WEIGHT smallint,
        primary key (USER_ID)
    );
    create table PATIENT (
        USER_ID bigint not null,
        ACCOUNT_ID bigint,
        primary key (USER_ID)
    );
    create table POST (
        ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        TEXT longvarchar,
        PARENT_ID bigint,
        POST_BY varchar(255),
        QUERY_ID bigint,
        USER_ID bigint,
        primary key (ID)
    );
    create table QUERY (
        ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        DOCTOR_ID bigint,
        PATIENT_ID bigint,
        primary key (ID)
    );
    create table ROLE (
        ROLE_NAME varchar(255) not null,
        primary key (ROLE_NAME)
    );
    create table SERVICE_PLAN (
        SERVICE_PLAN_ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        DURATION varchar(255),
        FEE integer,
        NAME varchar(255),
        DEPENDENTS smallint,
        primary key (SERVICE_PLAN_ID)
    );
    create table SPECIALITIES (
        SPECIALITY varchar(255) not null,
        primary key (SPECIALITY)
    );
    create table USER (
        USER_ID bigint generated by default as identity (start with 1),
        UPDATED_ON_DATE timestamp,
        FIRST_NAME varchar(255),
        LAST_NAME varchar(255),
        LOGIN_NAME varchar(255),
        LOGIN_TYPE varchar(255),
        PASSWORD varchar(255),
        CONTACT_ID bigint,
        ROLE_NAME varchar(255),
        primary key (USER_ID)
    );
    alter table ACCOUNT 
        add constraint FK_7omua1d0x1aw82jx3tr950t4j 
        foreign key (ADMIN_ID) 
        references PATIENT;
    alter table ACCOUNT 
        add constraint FK_h2fesrbra310qxqgkhlv2kova 
        foreign key (SERVICE_PLAN_ID) 
        references SERVICE_PLAN;
    alter table ADMIN 
        add constraint FK_k7nbdad3rdc84ktsr6ywe2x9b 
        foreign key (USER_ID) 
        references USER;
    alter table CORPORATION 
        add constraint FK_9nn0pvva2jxbwq2jyouhup2x0 
        foreign key (ADMIN) 
        references ADMIN;
    alter table CORPORATION 
        add constraint FK_pk45adcdth6d77vh66s4r63b9 
        foreign key (CONTACT_ID) 
        references CONTACT_INFO;
    alter table CORPORATION 
        add constraint FK_rew8k2e3cyndcqib0mrvps6wp 
        foreign key (SERVICE_PLAN_ID) 
        references SERVICE_PLAN;
    alter table CORP_ACCOUNT 
        add constraint FK_165ph5rflumrseagqkubo2dqx 
        foreign key (ACCOUNT_ID) 
        references ACCOUNT;
    alter table CORP_ACCOUNT 
        add constraint FK_eo9gtb3906qhv5a56h3d2qhcs 
        foreign key (CORP_ID) 
        references CORPORATION;
    alter table DOCTOR 
        add constraint FK_bqb8yjsv3tah3cv3t6gkiffll 
        foreign key (USER_ID) 
        references USER;
    alter table DOCTOR_SPECIALITY 
        add constraint FK_4gy7w59b448p1xhcbsxq63i32 
        foreign key (SPECIALITY) 
        references SPECIALITIES;
    alter table DOCTOR_SPECIALITY 
        add constraint FK_egca66ybkaxfo7siw44t2yaav 
        foreign key (DOCTOR_ID) 
        references DOCTOR;
    alter table MEDICAL_INFORMATION 
        add constraint FK_8y8bynvisqk2de1u41m9v4obf 
        foreign key (USER_ID) 
        references PATIENT;
    alter table PATIENT 
        add constraint FK_ot9j4tfsw1t71b8rcyx834aqh 
        foreign key (ACCOUNT_ID) 
        references ACCOUNT;
    alter table PATIENT 
        add constraint FK_5p6pgn2g3f44n8anbke9newld 
        foreign key (USER_ID) 
        references USER;
    alter table POST 
        add constraint FK_j4o62xxv150favs5w0b2qnfi5 
        foreign key (PARENT_ID) 
        references POST;
    alter table POST 
        add constraint FK_mwj0v2jsekedtfjmcjv8vf94d 
        foreign key (POST_BY) 
        references ROLE;
    alter table POST 
        add constraint FK_mycmmtvk6n6h32je239rphmxx 
        foreign key (QUERY_ID) 
        references QUERY;
    alter table POST 
        add constraint POST_USER_FK 
        foreign key (USER_ID) 
        references USER;
    alter table QUERY 
        add constraint FK_a8eg91sahkelrceaa9hj88c3e 
        foreign key (DOCTOR_ID) 
        references DOCTOR;
    alter table QUERY 
        add constraint FK_ayadn6tibv24ao9nw4vu9wb2a 
        foreign key (PATIENT_ID) 
        references PATIENT;
    alter table USER 
        add constraint FK_eelbniam4xib643byg7mxphai 
        foreign key (CONTACT_ID) 
        references CONTACT_INFO;
    alter table USER 
        add constraint FK_qdvdtpmmuhsc8duxd628w530p 
        foreign key (ROLE_NAME) 
        references ROLE;