INSERT INTO ROLE VALUES ('DOCTOR');
INSERT INTO ROLE VALUES ('PATIENT');
INSERT INTO ROLE VALUES ('ADMIN');
INSERT INTO SERVICE_PLAN (DURATION, DEPENDENTS, FEE, UPDATED_ON_DATE, NAME) VALUES ('YEARLY', '4', '1000', '2014-11-28 15:43:35', 'BASIC');